server:
  port: 80
spring:
  messages:
    basename: i18n/messages
    encoding: utf-8
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?useSSL=true&useUnicode=true&characterEncoding=utf-8
    username: root
    password: admin
    type: com.alibaba.druid.pool.DruidDataSource
    dbcp2:
      min-idle: 5
      initial-size: 10
      max-total: 100
      max-wait-millis: 2000
    filters: stat,wall
mybatis:
  config-location: classpath:mybatis.cfg.xml
  type-aliases-package: com.baidu.firstboot.vo
  mapper-locations:
    - classpath:mapper/**/*.xml
logging:
  level:
    com.baidu.firstboot.dao: debug